### ISSUE TITLE
Overlay jedes Mal anzeigen

### ISSUE THREAD

**Issue by Schmidty2** [ErdmannFreunde/euf_overlay#10]
Hallo,
kann eine Option eingefügt werden, so dass das Overlay bei jedem Seitenaufruf angezeit wird.
Wenn die Speicherzeit des Cookies auf 0 steht, wird das Overlay nur einmal am Tag angezeigt.

Usercase: Auf der Seite einer Hilfsorganisation sollen bei Bedarf Warnmeldungen z:B. Hochwasser etc. bei jedem Aufruf der Seite im Overlay angezeigt werden.

**Comment by denniserdmann** [comment]
Moin!

Gute Idee, den Vorschlag haben wir auch per Mail schonmal bekommen. Momentan haben wenig Zeit, um die Erweiterung weiter zu entwickeln. Du kannst sie aber gerne selbst weiterentwickeln (und einen Pull-Request stellen) oder uns damit beauftragen, die  Erweiterung an deine Bedürfnisse anzupassen.

**Comment by GOVILI** [comment]
Würde ich auch unterstützen. Wäre auch toll, wenn darüber auf das Cookie generell verzichtet werden könnte.

**Comment by cmartin6** [comment]
Wie sieht es mit diesem Feature-Request aus? Ich würde dies ebenso benötigen...
