### ISSUE TITLE
Close Button

### ISSUE THREAD

**Issue by Witti2** [ErdmannFreunde/euf_overlay#13]
The Close button shows no function, no script error is ejected. Registered is the click on the button, however, because with a reload the popup is closed and the cookie was set.

**Comment by denniserdmann** [comment]
Sounds like https://github.com/ErdmannFreunde/euf_overlay/issues/9 

Do you have jQuery and Mootools loaded at the same time? In this case an error should appear when you click the close button (not when the site is loaded).

**Comment by Witti2** [comment]
I had already posted in the forum that the extension did not work for me, so I had already gotten a fix so that the no_conflict mode is on. Now it works with Mootools, only the Close Button does not work. Spooky has already looked at that and did not know why it was "For some reason, the toggle () does not work"

**Comment by denniserdmann** [comment]
I added the confict mode and double checked the close button. Working like a charm. If you still have problems with it, please re-open this ticket.
