### ISSUE TITLE
Overlay schliessen / Seite nicht scrollbar

### ISSUE THREAD

**Issue by planepix** [ErdmannFreunde/euf_overlay#17]
Hallo Dennis,
wohl aktuell eine der meist genutzten Bundles! Danke.

Vor drei Tagen in einer Website eingebaut ( Version 1.2.2) : funktioniert wunderbar.
Heute in eine Seite eingebaut: Hier bleibt nach dem Schliessen des Overlays (Klick auf close Button oder außerhalb) der Seiteninhalt schlicht stehen. Kein Scrollen mehr möglich.
Erst nach einem Reload der Seite ist sie wieder scrollbar.

Außer Anpassungen im CSS keine Änderungen vorgenommen.
Im Code-Inspektor keine JS-Fehler.

Contao 4.4.47
Website: https://www.bohnenstrolche.de/

Ich kann nicht beurteilen ob die Änderungen in der 1.2.4 dafür ausschlaggebend sind - vielleicht hast du eine Idee.

Danke dir und einen sonnigen Sonntag
Thomas

// EDIT: Ich habe jetzt erstmal die Version 1.2.2 installiert - dann ist die Website nach dem Schliessen wieder scroll- und erreichbar.

Wenn ich noch mal eine Testinstallation aufbereiten soll zum Fehler feinden, mach ich das gerne.

**Comment by denniserdmann** [comment]
Moin Thomas,
hast du bei der Installation jQuery und Mootools parallel im Einsatz?

**Comment by planepix** [comment]
Moin Dennis,
nein war nur jQuery aktiv.

Kurioserweise habe ich das Bundle (1.2.4) heute in einer anderen 4.4.47 Installation installiert.
Dort lässt sich die Website nach schliessen des Layers auch bedienen.

Hilft es die beiden composer.json zu posten?

**Comment by denniserdmann** [comment]
Ich denke, damit können wir die Contao Version als Problem ausschließen.

Es könnte an der Konfiguration von Contao und/oder verwendeten Erweiterungen liegen. Vielleicht kannst du den Fehler weiter eingrenzen, indem du dir die anderen Scripte ansiehst (verwendest bei dem einen Projekt j_accordion und bei den anderen nicht?) oder hast du die Scriptzusammenfassung aktiviert/deaktiviert? Ich werde aller Voraussicht erst am Donnerstag dazu kommen, mir das Problem genauer anzusehen.

**Comment by planepix** [comment]
Danke dir für deine Rückmeldung.
j_accordion ist in der Installation, in der die Version 1.2.4 nicht lief, aktiv. Scriptezusammenfassung ist nicht aktiv.

**Comment by chriza** [comment]
Ich habe auch das Problem.
In den js Dateien habe ich ein Thema gefunden: In der function closeOverlay fehlt die Behandlung des html-Tags. Es wird nur das Overlay geschlossen.

**Comment by denniserdmann** [comment]
Der Fehler sollte mit Version 1.2.5 behoben sein
