### ISSUE TITLE
Overlay schließen bei Link im Text

### ISSUE THREAD

**Issue by 9teufel** [ErdmannFreunde/euf_overlay#18]
Das Overlay kann ja mittels Klick auf das X oder den Overlay Hintergrund geschlossen werden.

Ist jedoch im Overlay-Text ein Link zu einer Unterseite und wird dieser geklickt, so wird das Overlay immer wieder geöffnet. Eventuell kann man einfügen dass Links im Overlay automatisch auch den Cookie setzen bzw. wäre eine Klasse hilfreich die man dem Link zuweist um den Cookie setzen zu lassen.

**Comment by homberger** [comment]
Das ist mit der Klasse `euf_overlay__close` möglich.
Also zum Beispiel so: `<a class="euf_overlay__close" href="/info">Info</a>`

**Comment by 9teufel** [comment]
Stimmt, das ist möglich. Die CSS Klasse muss dann jedoch umgeschrieben werden. 

```
a.euf_overlay__close {
    background: none;
    position: relative;
    top: auto;
    right: auto;
    padding: 0;
    font-weight:normal
}

a..euf_overlay__close:hover {
     opacity:1
}


```

Darum wäre eine eigene Klasse eine gute Lösung.

**Comment by homberger** [comment]
Das wäre natürlich noch deutlich besser :)

**Comment by denniserdmann** [comment]
Ich habe in https://github.com/ErdmannFreunde/euf_overlay/commit/31a820ce7ccb1d21b01bf817e889abab947cb1c2 eine zusätzliche Klasse `.euf_overlay__accept` eingeführt, die dafür verwendet werden kann.

Bitte einmal mit dem aktuellen develop-Branch testen.

**Comment by 9teufel** [comment]
Danke - funktioniert!

**Comment by denniserdmann** [comment]
Danke dir. Ich mache morgen nochmal ein paar Tests und dann geht die 1.2.6 online
