### ISSUE TITLE
Weitere Option, wann das Overlay eingeblendet wird

### ISSUE THREAD

**Issue by bastibuck** [ErdmannFreunde/euf_overlay#2]
Eine weitere sinnvolle Option das Overlay anzuzeigen, wäre nachdem ein Besucher einen bestimmbaren Prozentsatz der Webseite gescrollt hat (ggf. abhängig von einem TimeOut, um schneller "überscrollen" vom Trigger auszuschließen).

Involvement/Engagement zeigt sich auch durch wie weit ein Besucher liest und damit scrollt.

**Comment by bastibuck** [comment]
Feature fertig. 

Änderungen:
- neue Option: nach Scrollen von x %
- Code-Qualität und -Konsistenz erhöht

See https://github.com/ErdmannFreunde/euf_overlay/commit/8badc42b9bdeaa015197075466b7f32832f68d93 

Release als 1.1.0?

**Comment by denniserdmann** [comment]
sieht gut aus. Kannst du gerne veröffentlichen

**Comment by bastibuck** [comment]
Erledigt.
