### ISSUE TITLE
Mobil nicht mehr scrollbar

### ISSUE THREAD

**Issue by samazaphikel** [ErdmannFreunde/euf_overlay#20]
Hi,

ich habe mir das Plugin installiert und möchte auf etwas hinweisen.

Wenn man wie in der Beschreibung angegeben das Plugin im Footer integriert, dann kann es vorkommen das die Mobile Seite nicht mehr Scrollbar ist. Durch den Emulator fällt das nicht auf, da ist noch alles ok. Aber in der Praxis wird es auf einigen Smartphones nicht gehen. Komischer Weise aber nicht bei allen. Habe jetzt festgestellt das es überwiegend auf Huawai Geräten Probleme gibt.

Das Overlay ist auf dem Desktop PC relativ Mittig auf dem Bildschirm zu sehen und kann somit schön gelesen werden.

Auf dem Problem Smartphone Geräten, ist das Overlay nicht im Sichtbereich, das ist weiter unten und dadurch kommt es dazu, dass man das Overlay nicht wegklicken kann und dementsprechend nicht scrollen kann.

Ich habe für mich das so gelöst, dass ich das Overlay nur auf Desktop anzeigen lasse.

**Comment by denniserdmann** [comment]
>Auf dem Problem Smartphone Geräten, ist das Overlay nicht im Sichtbereich, das ist weiter unten und dadurch kommt es dazu, dass man das Overlay nicht wegklicken kann und dementsprechend nicht scrollen kann.

Kannst du das Problem mit einem Screenshot verdeutlichen? Danke!

**Comment by samazaphikel** [comment]
Ich wüsste nicht, wie man das auf einem Screenshot verdeutlichen könnte.

Das Overlay ist ja außerhalb des Sichtbereiches

**Comment by denniserdmann** [comment]
Ok, dann lass ich das Ticket einfach erstmal so stehen. Vielleicht hat noch jemand einen Tipp.

Ich habe leider kein passendes Gerät, um es nachvollziehen zu können. Aber es könnte zum Beispiel an einem `position: relative` des `#footer` liegen, sprich eigene CSS-Anweisungen könnten das Problem verursachen.

**Comment by samazaphikel** [comment]
Ich habe mal 2 Bilder gemacht, einmal mit Tablet view und einmal mit Smartphone view. CSS selber habe ich nichts angepasst. Ich nutze das Mate Theme.

![Unbenannt1](https://user-images.githubusercontent.com/35742942/87017078-cffbd400-c1cf-11ea-95c4-28daff1246b2.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/35742942/87017081-d0946a80-c1cf-11ea-9314-536a41b8b4fe.PNG)

**Comment by denniserdmann** [comment]
Ich habe ein paar Tests mit dem Mate Theme gemacht und vermute, dass das Problem dort liegt. Wenn der Eltern-Container eine Kombination aus folgenden Eigenschaften hat, wird das Overlay u.U. nicht dargestellt:

```
.parent {
  position: relative;
  z-index: 1; // beliebiger Wert
  overflow: hidden;
 height: 100px; // beliebiger Wert, auch min- und max-height
}
```

Das scheint beim Mate Theme der Fall zu sein. Du kannst versuchen, das Modul in einen anderen Bereich zu verschieben, sodass dieses Problem nicht auftritt.

**Comment by samazaphikel** [comment]
Ja, es liegt definitiv am Mate Theme.

Nachdem ich das im Footer etwas hin und hergeschoben habe, lag das Overlay dann irgendwann hinter dem Slider oben.

Habe dann in der overlay_default.css etwas angepasst:
```
.euf_overlay {
  display: none;
  position: fixed;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  background: rgba(0,0,0,0.7);
  **z-index:9;**
}
```

Nun scheint es richtig angezeigt zu werden. Ich übernehme das jetzt noch auf die custom.css, so dass es auch updatesicher ist.
