### ISSUE TITLE
Overlay wird nicht angezeigt

### ISSUE THREAD

**Issue by S-Snowball** [ErdmannFreunde/euf_overlay#21]
Hi,

ich habe die Erweiterung installiert und eingerichtet, aber es wird im FE nicht angezeigt.

zuerst habe ich ein Modul angelegt und als Modultyp das EuF-Overlay ausgewählt. Dort habe ich bei Seitenaufruf ausgewählt und Cookie Gültigkeit auf 1.

Im Footer habe ich dieses Modul ausgewählt und aktiviert.

Wenn ich nun das Frontend aufrufe, dann plopt fas allerdings nicht aus. Im Seitenquelltext ist das Modul allerdings sichtbar.

```
<div class="col m3 s12">
 <div class="mod_article block" id="article-208">
 <div id='euf_overlay' class='euf_overlay' data-moduleid='384' data-expires='1'>
 <div class='euf_overlay__content mod_euf_overlay block'>
 <button class='euf_overlay__close'>
 &times;
</button>
....

```

Muss ich noch eine bestimmte jQuery laden, dass das Modul aufplopt? Also jQuery selber ist im Theme aktiviert.

**Comment by denniserdmann** [comment]
Nein, das sollte reichen. 

Kannst du mal prüfen, ob das Overlay vielleicht verdeckt wird? 
Oder bekommst du einen JS-Fehler, wenn du in die DevTools-Console schaust? JS ist ein bisschen empfindlich. Auch Fehler, die von anderen Erweiterungen/Scripten verursacht werden,  können dazu führen, dass das Overlay nicht zu sehen ist.

**Comment by S-Snowball** [comment]
Bin jetzt erst dazu gekommen mir das nochmal anzusehen.

Ich habe die Erweiterung auf eine ältere Version Downgegradet und dann wieder auf die neueste Version Aktualisiert. Nun wird es korrekt angezeigt.
Woran das liegt, keine Ahnung. vermute aber mal in irgendeiner Form ein Fehler im Cache, obwohl ich alle gelöscht habe. Auch Browser Cache komplett gelöscht war.

**Comment by S-Snowball** [comment]
Ich habe gerade noch eine Frage.

Uns zwar trage ich im Overlay Modul im Bereich **Overlay-Inhalt: HTML** eine Zusätzliche Schaltfläche ein:
```
<form action="link zu einer internen Seite hier">
      <button type="submit" class="btn btn-primary">Mehr Informationen</button>
</form>
```

Wie könnte ich beim Klicken zusätzlich das Overlay Cookie setzen?

**Comment by denniserdmann** [comment]
Du kannst mal probieren, die zusätzliche Klasse `.euf_overlay__accept` an deinen Button zu hängen. Diese Klasse macht das gleiche wie der Schließen-Button und kann auch für Text-Links verwendet werden, siehe #18
