### ISSUE TITLE
Overlay wird nicht angezeigt

### ISSUE THREAD

**Issue by samazaphikel** [ErdmannFreunde/euf_overlay#26]
Hi,

ich habe mir das EUF heute auf Contao 4.10.3 installiert. 
Das Modul angelegt und im Footer das Modul eingepflegt.

Leider ploppt bei mir Garnichts auf. Auch im Seiten Quelltext ist nichts vom Overlay zu sehen.
In den Entwicklertools im Browser konnte ich keine Fehler feststellen.

 Was muss ich noch machen, das das Overlay angezeigt wird?

**Comment by denniserdmann** [comment]
Moin!

Nein, mehr muss man eigentlich nicht machen. Es könnte tatsächlich an der Contao Version liegen. Unter 4.9 läuft die Erweiterung noch, unter 4.10 und neuer habe ich sie noch nicht im Einsatz.

Wenn du den **Debug-Modus** aktivierst, müsstest du dann aber einen Fehler bekommen, der uns bei der Eingrenzung helfen könnte.

**Comment by samazaphikel** [comment]
Sorry, mein Fehler...

Hatte es in der Kopfzeile. Habe das jetzt in die Hauptspalte, nun geht es perfekt ohne Änderungen.

Muss lediglich die Farben auf das bestehende Dessign anpassen.

Also, somit läuft ohne zutun auf der 4.10.3
