### ISSUE TITLE
Cookie-Name um Modul-ID erweitern

### ISSUE THREAD

**Issue by bastibuck** [ErdmannFreunde/euf_overlay#3]
Derzeit kann nur ein Overlay pro Installation verwendet werden, da alle Overlays den gleichen Cookie-Namen verwenden. Hier sollte pro Modul ein eigener Name verwendet werden können, so dass man auch mehrere Module einbinden kann (bspw. abhängig von der Seite/Zielgruppe/etc.).

Meinungen?

**Comment by denniserdmann** [comment]
Das habe ich auch schon bemerkt. Für den normalen Nutzer reicht das ja, aber bei umfangreichen Seiten können 2 oder mehr Overlays für verschiedene Seiten sinnvoll sein. Mein Vorschlag wäre jetzt, das Cookie anhand der Modul-ID zu kennzeichnen. Extra einen Namen festzulegen finde ich nicht so gut.

**Comment by bastibuck** [comment]
Ja, auch eine gute Idee. 
Können wir ja für nächste Version mal sammeln.

**Comment by bastibuck** [comment]
Fixed in https://github.com/ErdmannFreunde/euf_overlay/commit/aba097925cfa2e5e8f44196bf054f13d3c1634e2
