### ISSUE TITLE
CSRF Problem, wenn Cookie per JavaScript gesetzt wird

### ISSUE THREAD

**Issue by kreadiv** [ErdmannFreunde/euf_overlay#32]
Liebes Team, 

ich habe mein Problem schon im Forum gepostet:

https://community.contao.org/de/showthread.php?84823-Ung%C3%BCltiges-Anfrage-Token-in-Verbindung-mit-Cookie-der-gesetzt-wird&p=570643#post570643

Auf einer Formular-Seite sorgt der Cookie, welcher per JavaScript zur Laufzeit gesetzt wird, dafür, dass das Formular einen gültigen CSRF-Token enthalten muss. Dieser ist aber nicht vorhanden, weil beim Aufruf der Seite noch kein Cookie gesetzt war.

Eine evtl. Lösung wäre es vielleicht, statt Cookies den Web Storage zu nutzen?

Aktuell muss ich die CSRF-Prüfung in der Config deaktivieren. Das ist aber auch keine Dauerlösung.

**Comment by denniserdmann** [comment]
Moin!

Wie an mehreren Stellen erwähnt, müsste die Erweiterung eigentlich mal an den aktuellen Stand der Technik angepasst werden. Allerdings haben wir momentan keine Zeit, die Erweiterung unentgeltlich zu überarbeiten.

Würden sich ein paar Leute finden, die mindestens 50% des Rewrites finanzieren würden, dann wäre ich auch bereit die Erweiterung mit LocalStorage und ein paar neuen Features neu aufzusetzen.

**Comment by kreadiv** [comment]
Hallo Dennis,
danke für dein Feedback. Das ist verständlich und habe ich mir schon gedacht.

Grüße Flo

**Comment by pirogis** [comment]
wie hoch sind denn diese 50%?

**Comment by denniserdmann** [comment]
Ich empfehle mittlerweile diese Erweiterung als Ersatz: https://extensions.contao.org/?q=xirdion%2Fcontao-modal-bundle&p=xirdion%2Fcontao-modal-bundle

Das macht eine Neuentwicklung nicht länger notwendig.
