### ISSUE TITLE
Contao 4 - Composer.json anpassen, damit Installation funktioniert

### ISSUE THREAD

**Issue by designpilot** [ErdmannFreunde/euf_overlay#4]
Ich musste die Erweiterung **euf_overlay** in **Contao 4.4.2** manuell installieren (im CM war diese zwar für die Installation ersichtlich "ohne Hinweis das diese nicht kompatibel sei" aber konnte nicht über den CM installiert werden, da in betreffender Datei der Versionshinweis fehlt).

**Manuelle Installation:**
- den entpackten ZIP Ordner "euf_overlay-master" von GitHub umbenennen in "euf_overlay"
- den Ordner "euf_overlay" auf den Webserver in das Verzeichnis ./system/modules laden
- im CM auf Systemwartung -> Cache neu erstellen
- im CM auf Tools und den Link für das Installtool klicken
- im Installtool die DB aktualisieren

Soweit ist die Installation sauber durchgelaufen und im BE dann beim erstellen eines neuen FE Modules wird auch alles korrekt angezeigt (keine Fehlermeldungen).

--------------------------------------------------------------------------------------------------

I had to install the extension euf_overlay in Contao 4.4.2 manually (in the CM it was shown for the installation "without notice this is not compatible" but could not be installed via the CM because the corresponding file is missing the version hints).

**Manual installation:**
- Rename the unpacked ZIP folder "euf_overlay-master" from GitHub to "euf_overlay"
- Load the folder "euf_overlay" on the web server in the directory ./system/modules
- In CM on System Maintenance -> Rebuild Cache
- In CM the overlay window, click on the link for the install tool
- In the install tool update the DB

As far as the installation went through cleanly and in the BE then when creating a new FE module everything is also displayed correctly (no error messages).

**Comment by bastibuck** [comment]
Danke für den Hinweis, bitte teste doch auch nochmal die Funktionalität im FE, dann können wir eine neue Version mit Contao 4.x freigeben.

**Comment by designpilot** [comment]
Ich habe die Funktionalität im FE getestet und in meinem Fall kann ich sagen das die 4 Ausgabemethoden funktionieren.

**Comment by bastibuck** [comment]
Cool, danke für den Hinweis!

**Comment by designpilot** [comment]
Hi Basti

Weisste was auch mal cool wär, wenn man an einem Contao Camp ein cooles Promo/Contao Video machen würd.

Weiste so mit Closeup/Cutoff Szenen das würd sicher noch reinhauen.


Freundliche Grüsse
Didier Federer
