### ISSUE TITLE
Contao 4 MIME-Typ-Konflikt

### ISSUE THREAD

**Issue by bit7ms** [ErdmannFreunde/euf_overlay#7]
Hallo,
habe die Anwendung manuell in Contao 4.4.7 installiert.
Leider kommt folgende Fehlermeldung in der Konsole:
```
Die Ressource von "http://xyz.de/system/modules/euf_overlay/assets/js/overlay_showAfterTime.js" wurde wegen eines MIME-Typ-Konfliktes blockiert (X-Content-Type-Options: nosniff).
Laden fehlgeschlagen für das <script> mit der Quelle "http://xyz.de/system/modules/euf_overlay/assets/js/overlay_showAfterTime.js". 
```
Was kann ich machen?

Besten Dank!

**Comment by denniserdmann** [comment]
Kannst du die angegebene Datei direkt über den Browser aufrufen? Wenn nicht, hast du die Symlinks neu anlegen lassen? Das Script im Assets-Ordner sollte durch einen Symlink in `web/system/modules/` verfügbar gemacht werden.

Ich habe die Erweiterung in einer Contao 4.4.7 laufen

**Comment by bit7ms** [comment]
hi, ja, danke. Scheint am Symlink gelegen zu haben. Merkwürdige Fehlermeldung...
