### ISSUE TITLE
Cookie-Gültigkeit in Tagen deaktivieren

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/euf_overlay#8]
Es wäre gut, wenn man die Cookie-Laufzeit auch deaktivieren könnte, so dass das Overlay wieder angezeigt wird, nachdem der Browser geschlossen wurde. Dies könnte man über die Cookie-Laufzeit „0 Tage“ realisieren.

**Comment by bastibuck** [comment]
Genau das mache ich derzeit schon in dem vorhandenen Feld. Funktioniert einwandfrei (siehe goandexplore Beispiel). 

Oder was meinst du?

**Comment by denniserdmann** [comment]
Denkfehler … sorry. Tab ungleich Browser.
