### ISSUE TITLE
Das Popup läßt sich nicht mit dem Kreuz schließen. 

### ISSUE THREAD

**Issue by kubjo** [ErdmannFreunde/euf_overlay#9]
Das Popup läßt sich nicht mit dem Kreuz schließen.

**Comment by denniserdmann** [comment]
Kannst du den Fehler weiter eingrenzen? Ich habe mehrere Websites mit der Erweiterung in der aktuellen Version am Laufen und dort funktioniert das Kreuz. Bekommst du einen Fehler in der Konsole?

**Comment by kubjo** [comment]
Soweit ich das beurteilen kann, nein. Habe im Firefox noch das alte Cookie drin das nur 1x am Tag das Popup zeigt, im Chrome keine Anzeige! Kann ich hier den URL posten?

**Comment by denniserdmann** [comment]
Nachtrag: Das Problem besteht nur, wenn Mootools und jQuery parallel im Einsatz sind.
